### ISSUE TITLE
No hit point in background Gotham.

### ISSUE THREAD

**Issue by mukesh14149** [fossasia/flappy-svg#70] opened 2016-02-07 11:03 UTC
While playing with background Gotham, there is no obstacle come in path, it is just going and going.
@niccokunzmann

**Comment by niccokunzmann** [comment] 2016-02-07 11:17
I guess, the problem is that the obstacles layer of Gotham is a background and not a obstacle layer.

Someone can comment and solve it :)

**Comment by mukesh14149** [comment] 2016-02-07 11:19
Yeah sure!

**Comment by mukesh14149** [comment] 2016-02-07 19:24
I think the obstacles layer of gotham is correct i.e Gotham_obstacles, but still this not working, when i change (createObstacles("Gotham_obstacles"); to createObstacles("cactus"); ) in method gothamShow() in background.js file it works fine but with Gotham_obstacles it doesn't work, can you help me little to resolve it @niccokunzmann

**Comment by niccokunzmann** [comment] 2016-02-07 19:35
Okay, I think the problem might be that only `g` objects (groups) are allowed as obstacles. We discussed this would need treatment. The problem could be [here](https://github.com/fossasia/flappy-svg/pull/44#discussion-diff-49937381). Obstacle collision still needs work but we have a basic version running.

**Comment by mukesh14149** [comment] 2016-02-07 19:56
g objects(groups) is used for every layer like background, SunAndMoon, sky, Gotham_obstacle, cactus etc so i tried replacing different layers for createObstacles(layer) and found only cactus layer react as obstacle.

**Comment by niccokunzmann** [comment] 2016-02-07 20:06
I am referring to 

    var list = layerNamed(layer).getElementsByTagName("g");

especially to `getElementsByTagName`. This line says that only group objects can be obstacles.

**Comment by mukesh14149** [comment] 2016-02-07 20:13
So its mean that only the tag name g can be can be a obstacles.

**Comment by mukesh14149** [comment] 2016-02-07 20:18
I think they are grouped.
![screenshot from 2016-02-08 01 47 26](https://cloud.githubusercontent.com/assets/10887629/12874982/f7999956-ce05-11e5-8353-08670824be08.png)

**Comment by niccokunzmann** [comment] 2016-02-07 20:32
This is only one grouped. Look further.... The creator used clones to keep the file size down. There are several objects: the one g object and the use objects, the clones.

**Comment by harry-7** [comment] 2016-08-05 17:09
@niccokunzmann  We can close this issue.

**Comment by niccokunzmann** [comment] 2016-08-05 17:15
Yes, #115 closes this.

**Closed by niccokunzmann** 2016-08-05 17:15 UTC
Labels: bug, easy
